// 150 emotional archetypes with sonic metadata
// Each maps a human emotional state to music generation parameters

export type Archetype = {
  id: string;
  text: string; // natural language description used for embedding
  mood: string;
  tempo: string;
  texture: string;
  instrumentation: string;
  key: string;
  dynamics: string;
  musicPrompt: string; // ready-made ElevenLabs prompt
};

export const archetypes: Archetype[] = [
  // --- ANXIETY & DREAD ---
  {
    id: "arch_001",
    text: "heart racing before something important, mind running through every possible outcome, shallow breathing",
    mood: "anxious anticipation",
    tempo: "moderate, slightly erratic",
    texture: "sparse, tense",
    instrumentation: "strings, prepared piano, subtle percussion",
    key: "D minor",
    dynamics: "soft to medium, sudden swells",
    musicPrompt: "tense ambient, sparse strings, prepared piano, minor key, erratic pulse, nervous energy, cinematic",
  },
  {
    id: "arch_002",
    text: "dread of something inevitable approaching, unable to stop what is coming",
    mood: "impending dread",
    tempo: "slow, inexorable",
    texture: "heavy, thick",
    instrumentation: "low brass, cello, deep synth pads",
    key: "B minor",
    dynamics: "building crescendo, oppressive",
    musicPrompt: "dark orchestral, low brass, cello drones, deep synth, slow build, ominous, cinematic dread",
  },
  {
    id: "arch_003",
    text: "social anxiety, feeling out of place in a crowd, everyone seems to be watching",
    mood: "social unease",
    tempo: "moderate",
    texture: "fragmented, dissonant",
    instrumentation: "chamber ensemble, out-of-tune piano, glitchy textures",
    key: "E minor",
    dynamics: "quiet, twitchy",
    musicPrompt: "chamber music, slightly dissonant, fragmented melody, sparse, uneasy, introspective, quiet",
  },
  {
    id: "arch_004",
    text: "late night catastrophizing, spiraling thoughts at 3am",
    mood: "midnight spiral",
    tempo: "slow with irregular timing",
    texture: "sparse, echoing",
    instrumentation: "solo piano, distant strings, subtle noise",
    key: "F minor",
    dynamics: "quiet, intimate",
    musicPrompt: "solo piano, sparse strings, minor key, late night introspective, melancholic, ambient, quiet",
  },
  // --- GRIEF & LOSS ---
  {
    id: "arch_005",
    text: "quiet grief after losing someone, sitting alone with memories",
    mood: "quiet grief",
    tempo: "slow",
    texture: "sparse, delicate",
    instrumentation: "solo cello, piano, silence",
    key: "G minor",
    dynamics: "very soft, fragile",
    musicPrompt: "solo cello, sparse piano, silence, slow, melancholic, fragile, intimate, grief",
  },
  {
    id: "arch_006",
    text: "first wave of loss hitting unexpectedly, realizing someone is gone",
    mood: "sudden grief",
    tempo: "moderate then slowing",
    texture: "open, raw",
    instrumentation: "strings, piano, wordless vocals",
    key: "C minor",
    dynamics: "building then collapsing",
    musicPrompt: "strings, piano, wordless vocals, raw emotion, sudden dynamics, grief, cinematic, orchestral",
  },
  {
    id: "arch_007",
    text: "missing someone who is still alive but gone from your life",
    mood: "longing for the living",
    tempo: "moderate",
    texture: "warm but hollow",
    instrumentation: "guitar, piano, soft strings",
    key: "A minor",
    dynamics: "gentle, bittersweet",
    musicPrompt: "acoustic guitar, piano, soft strings, bittersweet, longing, warm, melancholic, indie",
  },
  {
    id: "arch_008",
    text: "acceptance of loss, peace after grief, carrying someone in your heart",
    mood: "peaceful acceptance",
    tempo: "slow, steady",
    texture: "warm, resolved",
    instrumentation: "piano, strings, gentle pad",
    key: "F major",
    dynamics: "soft, resolving",
    musicPrompt: "piano, strings, resolved, warm, peaceful, acceptance, gentle, major key, healing",
  },
  // --- JOY & ELATION ---
  {
    id: "arch_009",
    text: "pure unexpected joy, something wonderful happening out of nowhere",
    mood: "spontaneous joy",
    tempo: "fast, bouncy",
    texture: "bright, full",
    instrumentation: "brass, piano, percussion, strings",
    key: "G major",
    dynamics: "loud, exuberant",
    musicPrompt: "bright orchestral, brass, piano, percussion, fast, joyful, exuberant, major key, celebratory",
  },
  {
    id: "arch_010",
    text: "quiet contentment, a perfect ordinary moment, everything feeling right",
    mood: "quiet contentment",
    tempo: "gentle, unhurried",
    texture: "warm, simple",
    instrumentation: "acoustic guitar, piano, soft woodwinds",
    key: "D major",
    dynamics: "soft, steady",
    musicPrompt: "acoustic guitar, piano, woodwinds, warm, simple, contented, folk, gentle, sunny",
  },
  {
    id: "arch_011",
    text: "euphoria, peak of excitement, on top of the world feeling",
    mood: "euphoria",
    tempo: "very fast",
    texture: "dense, soaring",
    instrumentation: "full orchestra, synths, driving rhythm",
    key: "E major",
    dynamics: "very loud, soaring",
    musicPrompt: "full orchestra, synths, driving rhythm, euphoric, soaring, epic, major key, powerful, triumphant",
  },
  {
    id: "arch_012",
    text: "childlike delight, wonder at something simple and magical",
    mood: "childlike wonder",
    tempo: "playful, moderate",
    texture: "light, sparkling",
    instrumentation: "glockenspiel, piano, pizzicato strings, flute",
    key: "C major",
    dynamics: "light, dancing",
    musicPrompt: "glockenspiel, pizzicato strings, flute, piano, playful, whimsical, wonder, light, magical",
  },
  // --- LOVE & CONNECTION ---
  {
    id: "arch_013",
    text: "falling in love, giddy excitement of new feelings",
    mood: "falling in love",
    tempo: "moderate, slightly rushed",
    texture: "warm, glowing",
    instrumentation: "piano, strings, soft synth",
    key: "A major",
    dynamics: "building, warm",
    musicPrompt: "piano, strings, soft synth, romantic, warm, building, gentle, hopeful, glowing",
  },
  {
    id: "arch_014",
    text: "deep familiar love, comfort of long-term partnership",
    mood: "enduring love",
    tempo: "slow, steady",
    texture: "rich, settled",
    instrumentation: "piano, cello, guitar",
    key: "G major",
    dynamics: "moderate, full",
    musicPrompt: "piano, cello, acoustic guitar, warm, settled, deep, intimate, romantic, steady",
  },
  {
    id: "arch_015",
    text: "unrequited love, loving someone who does not love you back",
    mood: "unrequited love",
    tempo: "moderate, yearning",
    texture: "open, aching",
    instrumentation: "solo violin, piano, sparse strings",
    key: "E minor",
    dynamics: "soft, longing",
    musicPrompt: "solo violin, piano, sparse strings, longing, aching, unrequited, bittersweet, minor key",
  },
  {
    id: "arch_016",
    text: "the moment of reunion after a long time apart",
    mood: "reunion",
    tempo: "moderate, swelling",
    texture: "warm, expanding",
    instrumentation: "strings, piano, subtle choir",
    key: "F major",
    dynamics: "building to full, emotional",
    musicPrompt: "strings, piano, choir, reunion, emotional, warm, swelling, cinematic, hopeful",
  },
  // --- ANGER & FRUSTRATION ---
  {
    id: "arch_017",
    text: "burning frustration, being blocked at every turn, nothing working",
    mood: "frustration",
    tempo: "fast, driving",
    texture: "thick, aggressive",
    instrumentation: "electric guitar, drums, distorted synth",
    key: "D minor",
    dynamics: "loud, punchy",
    musicPrompt: "electric guitar, drums, distorted synth, aggressive, driving, frustrated, rock, dark, intense",
  },
  {
    id: "arch_018",
    text: "cold controlled anger, barely keeping it together",
    mood: "controlled rage",
    tempo: "moderate, precise",
    texture: "tight, compressed",
    instrumentation: "low strings, brass, tense percussion",
    key: "C minor",
    dynamics: "restrained, threatening",
    musicPrompt: "low strings, brass stabs, tight percussion, controlled, tense, restrained anger, cinematic, dark",
  },
  {
    id: "arch_019",
    text: "righteous anger, fighting for what is right",
    mood: "righteous anger",
    tempo: "fast, march-like",
    texture: "powerful, driving",
    instrumentation: "brass, full orchestra, snare drum",
    key: "G minor",
    dynamics: "powerful, building",
    musicPrompt: "brass, full orchestra, snare, march, powerful, righteous, driving, heroic dark, determined",
  },
  {
    id: "arch_020",
    text: "petty irritation, small things piling up into annoyance",
    mood: "petty irritation",
    tempo: "moderate, slightly jittery",
    texture: "scratchy, dissonant",
    instrumentation: "pizzicato strings, woodwinds, dry percussion",
    key: "B minor",
    dynamics: "moderate, pointed",
    musicPrompt: "pizzicato strings, woodwinds, dry percussion, slightly comic, irritated, dissonant, chamber",
  },
  // --- FEAR ---
  {
    id: "arch_021",
    text: "primal fear, something hunting you in the dark",
    mood: "primal fear",
    tempo: "fast, erratic",
    texture: "chaotic, raw",
    instrumentation: "strings, brass clusters, pounding percussion",
    key: "atonal",
    dynamics: "explosive, unpredictable",
    musicPrompt: "strings clusters, brass, pounding drums, atonal, horror, primal fear, chaotic, intense, dark",
  },
  {
    id: "arch_022",
    text: "quiet existential fear, confronting your own mortality",
    mood: "existential fear",
    tempo: "very slow",
    texture: "vast, empty",
    instrumentation: "organ, distant choir, low drone",
    key: "C minor",
    dynamics: "quiet, vast",
    musicPrompt: "organ, distant choir, low drone, vast, existential, slow, dark ambient, contemplative",
  },
  {
    id: "arch_023",
    text: "fear of failure, standing at the edge of something that could go wrong",
    mood: "fear of failure",
    tempo: "moderate, hesitant",
    texture: "fragile, tense",
    instrumentation: "solo piano, sparse strings, held breath",
    key: "A minor",
    dynamics: "quiet, building",
    musicPrompt: "solo piano, sparse strings, tense, hesitant, fragile, cinematic suspense, quiet",
  },
  // --- HOPE & YEARNING ---
  {
    id: "arch_024",
    text: "hope after a dark period, first light of something better",
    mood: "emerging hope",
    tempo: "moderate, rising",
    texture: "clearing, brightening",
    instrumentation: "piano, strings, soft brass",
    key: "E major",
    dynamics: "quietly building",
    musicPrompt: "piano, strings, soft brass, hopeful, emerging, brightening, cinematic, warm, resolving",
  },
  {
    id: "arch_025",
    text: "longing for a place or time you cannot return to",
    mood: "nostalgia",
    tempo: "slow, drifting",
    texture: "hazy, warm",
    instrumentation: "piano, guitar, warm strings, slight reverb",
    key: "D major",
    dynamics: "soft, fading",
    musicPrompt: "piano, guitar, warm strings, reverb, nostalgic, hazy, bittersweet, slow, indie",
  },
  {
    id: "arch_026",
    text: "yearning for something you have never had but desperately want",
    mood: "aching yearning",
    tempo: "moderate, swelling",
    texture: "open, reaching",
    instrumentation: "strings, piano, solo oboe",
    key: "B minor",
    dynamics: "swelling, searching",
    musicPrompt: "strings, piano, solo oboe, yearning, searching, aching, cinematic, expansive, minor key",
  },
  {
    id: "arch_027",
    text: "tentative hope, scared to believe things might get better",
    mood: "fragile hope",
    tempo: "slow, careful",
    texture: "delicate, uncertain",
    instrumentation: "solo piano, distant strings",
    key: "F major",
    dynamics: "very soft, hesitant",
    musicPrompt: "solo piano, distant strings, fragile, tentative, hopeful, quiet, uncertain, intimate",
  },
  // --- EMPTINESS & NUMBNESS ---
  {
    id: "arch_028",
    text: "emotional numbness, feeling nothing at all, going through the motions",
    mood: "numbness",
    tempo: "very slow, mechanical",
    texture: "flat, colorless",
    instrumentation: "minimal synth, distant piano",
    key: "C minor",
    dynamics: "flat, no dynamics",
    musicPrompt: "minimal synth, distant piano, flat, colorless, numb, ambient, slow, monotone, cold",
  },
  {
    id: "arch_029",
    text: "the hollow feeling after a big event ends",
    mood: "post-event emptiness",
    tempo: "slow",
    texture: "empty, echoing",
    instrumentation: "reverbed piano, sparse strings",
    key: "G minor",
    dynamics: "fading, hollow",
    musicPrompt: "reverbed piano, sparse strings, hollow, empty, fading, post-climax, ambient, melancholic",
  },
  {
    id: "arch_030",
    text: "dissociation, watching yourself from outside, feeling unreal",
    mood: "dissociation",
    tempo: "moderate, floating",
    texture: "hazy, disconnected",
    instrumentation: "synth pads, filtered piano, glitch",
    key: "modal",
    dynamics: "dreamlike, distant",
    musicPrompt: "synth pads, filtered piano, glitch textures, hazy, dissociative, floating, dreamy, ambient",
  },
  // --- PRIDE & ACHIEVEMENT ---
  {
    id: "arch_031",
    text: "quiet satisfaction of finishing something difficult",
    mood: "quiet pride",
    tempo: "moderate, settled",
    texture: "warm, resolved",
    instrumentation: "piano, strings, gentle brass",
    key: "D major",
    dynamics: "moderate, content",
    musicPrompt: "piano, strings, gentle brass, settled, satisfied, warm, resolved, cinematic, major key",
  },
  {
    id: "arch_032",
    text: "triumph after long struggle, finally succeeding against all odds",
    mood: "triumph",
    tempo: "fast, powerful",
    texture: "full, majestic",
    instrumentation: "full orchestra, choir, timpani",
    key: "C major",
    dynamics: "fortissimo, majestic",
    musicPrompt: "full orchestra, choir, timpani, triumphant, majestic, powerful, epic, cinematic, major key",
  },
  {
    id: "arch_033",
    text: "pride in someone you love doing something incredible",
    mood: "vicarious pride",
    tempo: "moderate, warm",
    texture: "glowing, full",
    instrumentation: "strings, piano, gentle choir",
    key: "G major",
    dynamics: "warm, swelling",
    musicPrompt: "strings, piano, gentle choir, warm, proud, swelling, heartfelt, cinematic, major",
  },
  // --- LONELINESS ---
  {
    id: "arch_034",
    text: "loneliness in a crowd, surrounded by people but invisible",
    mood: "crowded loneliness",
    tempo: "moderate, drifting",
    texture: "layered but isolated",
    instrumentation: "solo piano, distant party sounds, strings",
    key: "A minor",
    dynamics: "quiet solo against background",
    musicPrompt: "solo piano, sparse strings, isolated melody, ambient background, lonely, urban, minor key",
  },
  {
    id: "arch_035",
    text: "solitude chosen and savored, being alone and loving it",
    mood: "chosen solitude",
    tempo: "slow, spacious",
    texture: "open, peaceful",
    instrumentation: "acoustic guitar, soft piano, nature sounds",
    key: "C major",
    dynamics: "quiet, breathing",
    musicPrompt: "acoustic guitar, piano, nature sounds, peaceful solitude, spacious, calm, folk, warm",
  },
  {
    id: "arch_036",
    text: "deep loneliness late at night, aching for connection",
    mood: "late night loneliness",
    tempo: "slow",
    texture: "sparse, cold",
    instrumentation: "solo piano, reverb, silence",
    key: "F minor",
    dynamics: "very quiet, aching",
    musicPrompt: "solo piano, heavy reverb, sparse, cold, late night, lonely, intimate, minor key, ambient",
  },
  // --- EXCITEMENT & ANTICIPATION ---
  {
    id: "arch_037",
    text: "electric anticipation, something amazing is about to begin",
    mood: "electric anticipation",
    tempo: "building, fast",
    texture: "rising, bright",
    instrumentation: "strings, synths, building drums",
    key: "A major",
    dynamics: "building to explosion",
    musicPrompt: "strings, synths, building drums, anticipation, electric, rising energy, cinematic, exciting",
  },
  {
    id: "arch_038",
    text: "excitement of travel, heading somewhere new and unknown",
    mood: "travel excitement",
    tempo: "moderate, forward-moving",
    texture: "expansive, open",
    instrumentation: "guitar, piano, light percussion, woodwinds",
    key: "D major",
    dynamics: "bright, energetic",
    musicPrompt: "acoustic guitar, piano, light percussion, woodwinds, travel, adventure, bright, open, indie folk",
  },
  {
    id: "arch_039",
    text: "nervous excitement before a first date",
    mood: "nervous excitement",
    tempo: "moderate, slightly rushed",
    texture: "light, fluttery",
    instrumentation: "piano, pizzicato strings, light percussion",
    key: "E major",
    dynamics: "light, giddy",
    musicPrompt: "piano, pizzicato strings, light percussion, nervous, excited, giddy, romantic, playful, light",
  },
  // --- SHAME & EMBARRASSMENT ---
  {
    id: "arch_040",
    text: "burning embarrassment after saying the wrong thing",
    mood: "embarrassment",
    tempo: "moderate, stumbling",
    texture: "cramped, awkward",
    instrumentation: "woodwinds, piano, awkward pauses",
    key: "G minor",
    dynamics: "quiet, shrinking",
    musicPrompt: "woodwinds, piano, awkward silences, stumbling, embarrassed, minor, chamber, uncomfortable",
  },
  {
    id: "arch_041",
    text: "deep shame, wanting to disappear, feeling fundamentally wrong",
    mood: "deep shame",
    tempo: "slow, collapsing",
    texture: "heavy, sunken",
    instrumentation: "low strings, bass clarinet, silence",
    key: "D minor",
    dynamics: "quiet and heavy",
    musicPrompt: "low strings, bass clarinet, heavy silence, shame, sinking, dark, quiet, oppressive, minor key",
  },
  // --- CONFUSION & UNCERTAINTY ---
  {
    id: "arch_042",
    text: "being at a crossroads, genuinely not knowing which way to go",
    mood: "crossroads uncertainty",
    tempo: "moderate, wandering",
    texture: "searching, unresolved",
    instrumentation: "piano, strings, unresolved harmonies",
    key: "modal",
    dynamics: "moderate, questioning",
    musicPrompt: "piano, strings, unresolved harmonies, wandering, searching, uncertain, modal, introspective",
  },
  {
    id: "arch_043",
    text: "confusion after something unexpected shatters your understanding",
    mood: "disorientation",
    tempo: "erratic",
    texture: "fractured, spinning",
    instrumentation: "strings, prepared piano, dissonant brass",
    key: "atonal",
    dynamics: "unpredictable",
    musicPrompt: "strings, prepared piano, dissonant, fractured, disoriented, atonal, cinematic, chaotic",
  },
  // --- PEACE & CALM ---
  {
    id: "arch_044",
    text: "deep calm, meditation, the mind going completely still",
    mood: "deep calm",
    tempo: "very slow, breathing",
    texture: "open, minimal",
    instrumentation: "singing bowls, soft pad, distant piano",
    key: "Eb major",
    dynamics: "barely there",
    musicPrompt: "singing bowls, soft synth pad, distant piano, meditative, calm, minimal, breathing, ambient",
  },
  {
    id: "arch_045",
    text: "peace by water, watching waves, mind emptying",
    mood: "coastal peace",
    tempo: "slow, rhythmic like waves",
    texture: "lush, open",
    instrumentation: "acoustic guitar, piano, ambient water, light strings",
    key: "G major",
    dynamics: "gentle, flowing",
    musicPrompt: "acoustic guitar, piano, water ambience, strings, waves, peaceful, coastal, flowing, warm",
  },
  {
    id: "arch_046",
    text: "morning calm before the world wakes up, quiet and still",
    mood: "morning stillness",
    tempo: "slow, unhurried",
    texture: "light, fresh",
    instrumentation: "solo piano, light strings, birdsong",
    key: "C major",
    dynamics: "soft, awakening",
    musicPrompt: "solo piano, strings, bird sounds, morning, fresh, still, quiet, peaceful, gentle awakening",
  },
  // --- DETERMINATION & RESOLVE ---
  {
    id: "arch_047",
    text: "steeling yourself to do something hard, choosing to keep going",
    mood: "determination",
    tempo: "moderate, steady",
    texture: "solid, grounded",
    instrumentation: "brass, strings, steady drums",
    key: "D minor",
    dynamics: "building, resolute",
    musicPrompt: "brass, strings, steady drums, determined, resolute, building, cinematic, dark hero, steady",
  },
  {
    id: "arch_048",
    text: "quiet resilience after being knocked down again",
    mood: "quiet resilience",
    tempo: "slow, then rising",
    texture: "sparse then filling",
    instrumentation: "solo piano, then strings joining",
    key: "A minor",
    dynamics: "quiet then building",
    musicPrompt: "solo piano, strings building, resilient, quiet strength, rising, cinematic, minor to hopeful",
  },
  {
    id: "arch_049",
    text: "defiance, refusing to back down when the world is against you",
    mood: "defiance",
    tempo: "fast, aggressive",
    texture: "hard, sharp",
    instrumentation: "electric guitar, drums, brass",
    key: "E minor",
    dynamics: "loud, sharp accents",
    musicPrompt: "electric guitar, drums, brass, defiant, aggressive, rock, sharp, intense, dark",
  },
  // --- NOSTALGIA & MEMORY ---
  {
    id: "arch_050",
    text: "sudden vivid memory of childhood triggered by a smell or sound",
    mood: "vivid nostalgia",
    tempo: "moderate, hazy",
    texture: "warm, dreamy",
    instrumentation: "music box, piano, warm strings",
    key: "F major",
    dynamics: "soft, glowing",
    musicPrompt: "music box, piano, warm strings, childhood nostalgia, dreamy, warm, glowing, memory",
  },
  {
    id: "arch_051",
    text: "looking through old photos, time passing faster than expected",
    mood: "poignant nostalgia",
    tempo: "slow",
    texture: "layered, distant",
    instrumentation: "piano, strings, vinyl crackle, distant voices",
    key: "G minor",
    dynamics: "bittersweet, soft",
    musicPrompt: "piano, strings, vinyl crackle, poignant, bittersweet, slow, nostalgic, time passing",
  },
  // --- SURPRISE & WONDER ---
  {
    id: "arch_052",
    text: "awe at something vast and incomprehensible, feeling small in the best way",
    mood: "awe",
    tempo: "very slow, expansive",
    texture: "vast, soaring",
    instrumentation: "full orchestra, choir, organ",
    key: "D major",
    dynamics: "massive, overwhelming",
    musicPrompt: "full orchestra, choir, organ, awe, vast, soaring, expansive, cinematic, overwhelming, grand",
  },
  {
    id: "arch_053",
    text: "pleasant surprise, something wonderful you did not expect",
    mood: "pleasant surprise",
    tempo: "moderate, bouncy",
    texture: "light, effervescent",
    instrumentation: "piano, pizzicato, light percussion",
    key: "G major",
    dynamics: "suddenly bright",
    musicPrompt: "piano, pizzicato strings, light percussion, bright, surprising, joyful, effervescent, playful",
  },
  // --- BOREDOM & RESTLESSNESS ---
  {
    id: "arch_054",
    text: "profound boredom, time crawling, wanting anything to happen",
    mood: "boredom",
    tempo: "very slow, repetitive",
    texture: "flat, repetitive",
    instrumentation: "minimal piano, drone",
    key: "C major",
    dynamics: "flat, unchanging",
    musicPrompt: "minimal piano, drone, repetitive, flat, slow, boring, monotonous, ambient, minimal",
  },
  {
    id: "arch_055",
    text: "restlessness, unable to sit still, needing to do something but not knowing what",
    mood: "restlessness",
    tempo: "moderate, shifting",
    texture: "jittery, searching",
    instrumentation: "piano, percussion, short string motifs",
    key: "A minor",
    dynamics: "moderate, unsettled",
    musicPrompt: "piano, percussion, short strings, restless, shifting, unsettled, searching, moderate pace",
  },
  // --- CURIOSITY ---
  {
    id: "arch_056",
    text: "deep curiosity, following a thread of wonder wherever it leads",
    mood: "curiosity",
    tempo: "moderate, playful",
    texture: "light, questioning",
    instrumentation: "flute, piano, pizzicato, light percussion",
    key: "C major",
    dynamics: "light, exploratory",
    musicPrompt: "flute, piano, pizzicato strings, light percussion, curious, playful, exploratory, light, whimsical",
  },
  // --- GRATITUDE ---
  {
    id: "arch_057",
    text: "deep gratitude, overwhelmed by how lucky you are",
    mood: "gratitude",
    tempo: "moderate, warm",
    texture: "full, open-hearted",
    instrumentation: "strings, piano, gentle choir",
    key: "E major",
    dynamics: "warm, swelling",
    musicPrompt: "strings, piano, gentle choir, gratitude, warm, open, swelling, heartfelt, major key, cinematic",
  },
  // --- GUILT ---
  {
    id: "arch_058",
    text: "guilt for something done or not done, replaying the moment",
    mood: "guilt",
    tempo: "slow, circling",
    texture: "heavy, recurring motif",
    instrumentation: "piano, low strings, recurring figure",
    key: "D minor",
    dynamics: "moderate, weighted",
    musicPrompt: "piano, low strings, recurring motif, guilt, heavy, circling, weighted, minor key, introspective",
  },
  // --- JEALOUSY & ENVY ---
  {
    id: "arch_059",
    text: "jealousy watching someone have what you want",
    mood: "jealousy",
    tempo: "moderate, simmering",
    texture: "tense underneath surface calm",
    instrumentation: "strings, piano, tense undertone",
    key: "F minor",
    dynamics: "outwardly quiet, internally boiling",
    musicPrompt: "strings, piano, tense undertones, simmering, jealousy, minor key, restrained, cinematic",
  },
  // --- RELIEF ---
  {
    id: "arch_060",
    text: "enormous relief when something you feared did not happen",
    mood: "relief",
    tempo: "moderate, releasing",
    texture: "tension releasing into warmth",
    instrumentation: "piano, strings resolving from minor to major",
    key: "C major resolving",
    dynamics: "releasing, exhaling",
    musicPrompt: "piano, strings resolving, tension to warmth, relief, exhaling, minor to major, cinematic, emotional",
  },
  // --- ADDITIONAL ARCHETYPES ---
  {
    id: "arch_061",
    text: "falling asleep while listening to rain, completely safe and warm",
    mood: "cozy safety",
    tempo: "very slow, drifting",
    texture: "warm, soft",
    instrumentation: "piano, rain, soft pad, distant strings",
    key: "F major",
    dynamics: "very soft, fading",
    musicPrompt: "piano, rain sounds, soft synth pad, strings, cozy, safe, sleepy, warm, ambient, drifting",
  },
  {
    id: "arch_062",
    text: "last day of something you loved, knowing it will never be the same",
    mood: "bittersweet ending",
    tempo: "slow",
    texture: "full but fading",
    instrumentation: "piano, strings, closing harmonies",
    key: "A major to minor",
    dynamics: "moderate then fading",
    musicPrompt: "piano, strings, bittersweet, ending, fading, major to minor, poignant, cinematic, closing",
  },
  {
    id: "arch_063",
    text: "the specific melancholy of Sunday evening as the weekend ends",
    mood: "sunday sadness",
    tempo: "slow, fading",
    texture: "warm but dimming",
    instrumentation: "piano, soft guitar, distant strings",
    key: "G minor",
    dynamics: "quiet, ending",
    musicPrompt: "piano, acoustic guitar, strings, sunday melancholy, slow, quiet, fading, bittersweet, indie",
  },
  {
    id: "arch_064",
    text: "the moment before sleep when the mind finally goes quiet",
    mood: "hypnagogic peace",
    tempo: "very slow, drifting",
    texture: "dissolving",
    instrumentation: "minimal piano, soft drone, fading",
    key: "Db major",
    dynamics: "barely there, fading",
    musicPrompt: "minimal piano, soft drone, dissolving, sleep, hypnagogic, fading, ambient, ultra quiet",
  },
  {
    id: "arch_065",
    text: "watching a sunset alone, a day ending, feeling philosophical",
    mood: "contemplative sunset",
    tempo: "slow, fading",
    texture: "golden, expansive",
    instrumentation: "guitar, piano, ambient strings",
    key: "Eb major",
    dynamics: "warm, fading",
    musicPrompt: "guitar, piano, ambient strings, sunset, golden, contemplative, warm, fading, cinematic",
  },
  {
    id: "arch_066",
    text: "driving alone at night with music loud, feeling completely free",
    mood: "night drive freedom",
    tempo: "moderate, steady",
    texture: "open, driving",
    instrumentation: "synths, guitar, steady beat, open space",
    key: "A minor",
    dynamics: "moderate, sustained",
    musicPrompt: "synths, electric guitar, steady beat, night drive, freedom, open road, cinematic, indie",
  },
  {
    id: "arch_067",
    text: "imposter syndrome, waiting to be found out as a fraud",
    mood: "imposter syndrome",
    tempo: "moderate, slightly rushed",
    texture: "thin, precarious",
    instrumentation: "piano, sparse strings, tense undertone",
    key: "E minor",
    dynamics: "quiet, tense",
    musicPrompt: "piano, sparse strings, tense, precarious, imposter, quiet anxiety, minor key, uncertain",
  },
  {
    id: "arch_068",
    text: "first day somewhere new, alone and unknown",
    mood: "new beginning vulnerability",
    tempo: "moderate, tentative",
    texture: "sparse, open",
    instrumentation: "solo piano, ambient space",
    key: "C major",
    dynamics: "quiet, beginning",
    musicPrompt: "solo piano, ambient space, tentative, new beginning, vulnerable, open, cinematic, minor to major",
  },
  {
    id: "arch_069",
    text: "flow state, completely absorbed in something creative",
    mood: "creative flow",
    tempo: "moderate, continuous",
    texture: "seamless, energized",
    instrumentation: "piano, synth, continuous motion",
    key: "D major",
    dynamics: "sustained, flowing",
    musicPrompt: "piano, synth, continuous motion, flow state, energized, focused, modern classical, seamless",
  },
  {
    id: "arch_070",
    text: "hearing a song that perfectly captures exactly how you feel",
    mood: "music recognition catharsis",
    tempo: "varies, emotional",
    texture: "resonant, releasing",
    instrumentation: "full arrangement, emotional peak",
    key: "A major",
    dynamics: "building to catharsis",
    musicPrompt: "full band, emotional peak, cathartic, resonant, releasing, cinematic, crescendo, heartfelt",
  },
  {
    id: "arch_071",
    text: "homesickness for a home you no longer have or cannot return to",
    mood: "homesickness",
    tempo: "slow, drifting",
    texture: "warm but hollow",
    instrumentation: "piano, guitar, distant strings",
    key: "G major",
    dynamics: "soft, aching",
    musicPrompt: "piano, acoustic guitar, distant strings, homesick, aching, warm memory, slow, folk, bittersweet",
  },
  {
    id: "arch_072",
    text: "that feeling of something clicking into place, sudden clarity",
    mood: "sudden clarity",
    tempo: "moderate, resolving",
    texture: "clearing, bright",
    instrumentation: "piano, strings, bright chord",
    key: "E major",
    dynamics: "resolving moment, bright",
    musicPrompt: "piano, strings, resolving harmony, clarity, bright, moment of understanding, hopeful, cinematic",
  },
  {
    id: "arch_073",
    text: "saying goodbye to someone not knowing if you will see them again",
    mood: "uncertain farewell",
    tempo: "slow",
    texture: "open, unresolved",
    instrumentation: "piano, strings, unresolved ending",
    key: "A minor",
    dynamics: "quiet, fading",
    musicPrompt: "piano, strings, unresolved, goodbye, uncertain, quiet, farewell, cinematic, minor key",
  },
  {
    id: "arch_074",
    text: "being forgiven for something you thought was unforgivable",
    mood: "forgiveness received",
    tempo: "slow, then warming",
    texture: "heavy then releasing",
    instrumentation: "piano, strings resolving",
    key: "F major",
    dynamics: "heavy then gentle",
    musicPrompt: "piano, strings, heavy to warm, forgiveness, resolving, emotional, cinematic, major, releasing",
  },
  {
    id: "arch_075",
    text: "the weight of a decision that will change everything",
    mood: "momentous decision",
    tempo: "slow, weighted",
    texture: "heavy, suspended",
    instrumentation: "piano, low strings, suspended chord",
    key: "C minor",
    dynamics: "heavy, suspended",
    musicPrompt: "piano, low strings, suspended chord, momentous, weighted, decision, cinematic, tense, slow",
  },
  {
    id: "arch_076",
    text: "watching someone you love grow into who they are meant to be",
    mood: "loving pride",
    tempo: "moderate, warm",
    texture: "full, glowing",
    instrumentation: "strings, piano, gentle choir",
    key: "D major",
    dynamics: "warm, swelling",
    musicPrompt: "strings, piano, choir, loving pride, warm, swelling, cinematic, major, heartfelt, gentle",
  },
  {
    id: "arch_077",
    text: "vulnerability of showing your true self for the first time",
    mood: "vulnerable authenticity",
    tempo: "slow, delicate",
    texture: "bare, open",
    instrumentation: "solo piano, silence",
    key: "E minor",
    dynamics: "very soft, exposed",
    musicPrompt: "solo piano, silence, bare, exposed, vulnerable, authentic, quiet, delicate, intimate",
  },
  {
    id: "arch_078",
    text: "the specific joy of being understood by another person",
    mood: "feeling understood",
    tempo: "moderate, warm",
    texture: "warm, resonant",
    instrumentation: "piano, cello, warm harmonies",
    key: "G major",
    dynamics: "warm, full",
    musicPrompt: "piano, cello, warm harmonies, understood, connection, warm, intimate, gentle, major key",
  },
  {
    id: "arch_079",
    text: "watching your city from above at night, feeling both tiny and vast",
    mood: "urban sublime",
    tempo: "slow, expansive",
    texture: "vast, glittering",
    instrumentation: "synths, piano, ambient sounds, strings",
    key: "A minor",
    dynamics: "expansive, glittering",
    musicPrompt: "synths, piano, ambient city, strings, urban, night, vast, glittering, cinematic, ambient",
  },
  {
    id: "arch_080",
    text: "finishing a book and grieving the world that is now over",
    mood: "book grief",
    tempo: "slow, closing",
    texture: "warm, ending",
    instrumentation: "piano, strings, soft close",
    key: "F major",
    dynamics: "soft, final",
    musicPrompt: "piano, strings, soft closing, bittersweet, finished, grief of ending, warm, gentle, final",
  },
  {
    id: "arch_081",
    text: "laughter until you cry, joy so intense it becomes tears",
    mood: "joyful tears",
    tempo: "fast then slowing",
    texture: "bright then softening",
    instrumentation: "piano, strings, laughter-like runs",
    key: "G major",
    dynamics: "bright then tender",
    musicPrompt: "piano, strings, bright runs, joyful tears, laughing, tender, major to gentle, warm, emotional",
  },
  {
    id: "arch_082",
    text: "the peace that comes from genuinely not caring what anyone thinks",
    mood: "liberated indifference",
    tempo: "easy, unhurried",
    texture: "loose, free",
    instrumentation: "acoustic guitar, piano, laid-back rhythm",
    key: "C major",
    dynamics: "easy, relaxed",
    musicPrompt: "acoustic guitar, piano, laid-back, free, unconcerned, easy going, indie, warm, relaxed",
  },
  {
    id: "arch_083",
    text: "first coffee in the morning before the world needs anything from you",
    mood: "morning sanctuary",
    tempo: "slow, quiet",
    texture: "warm, small",
    instrumentation: "piano, soft ambient, minimal",
    key: "F major",
    dynamics: "quiet, intimate",
    musicPrompt: "solo piano, warm ambient, morning, quiet, small sanctuary, intimate, soft, minimal, peaceful",
  },
  {
    id: "arch_084",
    text: "anticipating something so good you can hardly stand it",
    mood: "delicious anticipation",
    tempo: "building, fast",
    texture: "bright, rising",
    instrumentation: "strings, piano, rising figure",
    key: "E major",
    dynamics: "building to release",
    musicPrompt: "strings, piano, rising figures, anticipation, delicious, building, bright, major key, exciting",
  },
  {
    id: "arch_085",
    text: "the warmth of a group of people who all love the same thing",
    mood: "communal joy",
    tempo: "moderate, dancing",
    texture: "full, warm, together",
    instrumentation: "full band, folk, communal",
    key: "D major",
    dynamics: "warm, full, celebratory",
    musicPrompt: "full band, folk, communal, warm, together, dancing, celebration, major key, joyful, group",
  },
  {
    id: "arch_086",
    text: "the specific sadness of things ending that were never quite right",
    mood: "imperfect ending sadness",
    tempo: "slow, heavy",
    texture: "unresolved, heavy",
    instrumentation: "piano, strings, unresolved harmonies",
    key: "D minor",
    dynamics: "quiet, heavy",
    musicPrompt: "piano, strings, unresolved, imperfect ending, melancholic, minor key, heavy, introspective",
  },
  {
    id: "arch_087",
    text: "watching a storm roll in, the thrill of something powerful approaching",
    mood: "storm thrill",
    tempo: "building fast",
    texture: "electric, building",
    instrumentation: "orchestra, brass, timpani, rising",
    key: "B minor",
    dynamics: "building to thunderous",
    musicPrompt: "orchestra, brass, timpani, building storm, electric, powerful, cinematic, dramatic, rising",
  },
  {
    id: "arch_088",
    text: "being exactly where you are supposed to be at exactly the right time",
    mood: "perfect alignment",
    tempo: "moderate, settled",
    texture: "warm, full, right",
    instrumentation: "full warm arrangement",
    key: "G major",
    dynamics: "full, content",
    musicPrompt: "full warm arrangement, settled, right, aligned, content, major key, cinematic, warm, peaceful",
  },
  {
    id: "arch_089",
    text: "grief mixed with relief, mourning someone who was suffering",
    mood: "grief-relief",
    tempo: "slow, complex",
    texture: "layered, contradictory",
    instrumentation: "piano, strings, gentle resolution",
    key: "F major",
    dynamics: "heavy then gentle",
    musicPrompt: "piano, strings, complex emotion, grief and relief, gentle resolution, cinematic, bittersweet",
  },
  {
    id: "arch_090",
    text: "the quiet heroism of just getting through a hard day",
    mood: "quiet heroism",
    tempo: "moderate, steady",
    texture: "modest, resolute",
    instrumentation: "piano, strings, understated",
    key: "C major",
    dynamics: "quiet strength",
    musicPrompt: "piano, strings, understated, quiet heroism, steady, modest, cinematic, gentle strength, major",
  },
  {
    id: "arch_091",
    text: "joy of dancing alone in your room when no one can see",
    mood: "private joy",
    tempo: "fast, dancing",
    texture: "light, free",
    instrumentation: "synth pop, drums, bouncy bass",
    key: "A major",
    dynamics: "fun, energetic",
    musicPrompt: "synth, drums, bass, dancing, private joy, fun, energetic, pop, light, carefree",
  },
  {
    id: "arch_092",
    text: "the intimacy of being in a quiet library or bookshop",
    mood: "bookshop intimacy",
    tempo: "slow, quiet",
    texture: "warm, hushed",
    instrumentation: "piano, guitar, quiet ambient",
    key: "D major",
    dynamics: "very quiet, intimate",
    musicPrompt: "piano, acoustic guitar, hushed, intimate, warm, library, quiet, soft, indie, cozy",
  },
  {
    id: "arch_093",
    text: "the surreal feeling right after a car accident, time slowing down",
    mood: "traumatic surreal",
    tempo: "very slow, warped",
    texture: "warped, slow motion",
    instrumentation: "reversed piano, slowed strings, noise",
    key: "atonal",
    dynamics: "warped, surreal",
    musicPrompt: "reversed piano, slowed strings, noise, surreal, traumatic, slow motion, warped, disorienting",
  },
  {
    id: "arch_094",
    text: "making peace with not being the person you thought you would be",
    mood: "self-acceptance",
    tempo: "slow, settled",
    texture: "warm, resolved",
    instrumentation: "piano, acoustic guitar, soft strings",
    key: "C major",
    dynamics: "gentle, settled",
    musicPrompt: "piano, acoustic guitar, strings, self-acceptance, settled, warm, resolved, gentle, major key",
  },
  {
    id: "arch_095",
    text: "the courage it takes to ask for help",
    mood: "vulnerable courage",
    tempo: "slow, tentative then sure",
    texture: "fragile then strengthening",
    instrumentation: "piano, building strings",
    key: "E minor to major",
    dynamics: "quiet then warming",
    musicPrompt: "piano, strings building, vulnerable, courageous, fragile then strong, minor to major, hopeful",
  },
  {
    id: "arch_096",
    text: "realizing you have outgrown a friendship",
    mood: "outgrown connection",
    tempo: "slow, reflective",
    texture: "warm but distancing",
    instrumentation: "piano, guitar, soft strings",
    key: "G minor",
    dynamics: "soft, fading",
    musicPrompt: "piano, guitar, strings fading, bittersweet, outgrown, reflective, minor key, quiet, gentle",
  },
  {
    id: "arch_097",
    text: "finishing a run and feeling the endorphins hit",
    mood: "post-exercise euphoria",
    tempo: "fast, triumphant",
    texture: "bright, powerful",
    instrumentation: "driving beat, synths, bright melody",
    key: "D major",
    dynamics: "energetic, triumphant",
    musicPrompt: "driving beat, synths, bright melody, post-run, euphoric, energetic, triumphant, electronic",
  },
  {
    id: "arch_098",
    text: "the bittersweetness of watching children grow up",
    mood: "watching children grow",
    tempo: "moderate, gentle",
    texture: "warm, bittersweet",
    instrumentation: "piano, strings, music box",
    key: "F major",
    dynamics: "warm, bittersweet",
    musicPrompt: "piano, strings, music box, children growing, bittersweet, warm, gentle, time passing, major",
  },
  {
    id: "arch_099",
    text: "the strange comfort of being sad about something beautiful",
    mood: "beautiful sadness",
    tempo: "slow, lyrical",
    texture: "rich, melancholic",
    instrumentation: "strings, piano, lyrical melody",
    key: "D minor",
    dynamics: "full, lush",
    musicPrompt: "strings, piano, lyrical, beautiful sadness, melancholic, rich, slow, cinematic, lush",
  },
  {
    id: "arch_100",
    text: "standing at the edge of something new, terrified and ready",
    mood: "terrified readiness",
    tempo: "building, held breath",
    texture: "suspended, ready to burst",
    instrumentation: "orchestra, held chord, then release",
    key: "A minor to major",
    dynamics: "suspended then explosive",
    musicPrompt: "orchestra, held chord, suspended, terrified readiness, minor to major explosion, cinematic, epic",
  },
  // Archetypes 101-150
  {
    id: "arch_101",
    text: "the warmth of old friendship reconnecting after years apart",
    mood: "reconnected friendship",
    tempo: "moderate, warm",
    texture: "rich, familiar",
    instrumentation: "piano, guitar, strings",
    key: "G major",
    dynamics: "warm, comfortable",
    musicPrompt: "piano, guitar, strings, old friends, warm, reconnecting, major key, comfortable, heartfelt",
  },
  {
    id: "arch_102",
    text: "the surreal feeling of being in a place from your dreams",
    mood: "dream déjà vu",
    tempo: "slow, floating",
    texture: "hazy, dreamlike",
    instrumentation: "reverbed piano, synth, distant strings",
    key: "modal",
    dynamics: "dreamlike, shifting",
    musicPrompt: "reverbed piano, synth pads, distant strings, dream, déjà vu, surreal, floating, ambient",
  },
  {
    id: "arch_103",
    text: "the melancholy of an empty house after everyone has left",
    mood: "empty house melancholy",
    tempo: "slow, echoing",
    texture: "sparse, echoing",
    instrumentation: "piano, reverb, silence",
    key: "F minor",
    dynamics: "quiet, echoing",
    musicPrompt: "piano, heavy reverb, silence, empty house, echoing, sparse, melancholic, lonely, minor",
  },
  {
    id: "arch_104",
    text: "a slow burn of wanting, patience and desire mixed together",
    mood: "slow burn desire",
    tempo: "slow, smouldering",
    texture: "warm, restrained",
    instrumentation: "guitar, piano, slow beat",
    key: "A minor",
    dynamics: "slow, building restraint",
    musicPrompt: "guitar, piano, slow beat, smouldering, desire, restrained, slow burn, warm, sensual",
  },
  {
    id: "arch_105",
    text: "the clarity that comes from a long walk alone",
    mood: "walking clarity",
    tempo: "steady walking pace",
    texture: "open, forward",
    instrumentation: "acoustic guitar, piano, light strings",
    key: "C major",
    dynamics: "steady, clear",
    musicPrompt: "acoustic guitar, piano, strings, walking, clarity, open, forward movement, indie folk, bright",
  },
  {
    id: "arch_106",
    text: "pride mixed with sadness when your child no longer needs you the same way",
    mood: "parental bittersweet",
    tempo: "slow, warm",
    texture: "full then sparse",
    instrumentation: "piano, strings, gentle",
    key: "D major",
    dynamics: "warm then soft",
    musicPrompt: "piano, strings, parental love, bittersweet, growing up, warm then gentle, cinematic",
  },
  {
    id: "arch_107",
    text: "the specific joy of a perfect meal with people you love",
    mood: "convivial joy",
    tempo: "moderate, warm",
    texture: "full, lively",
    instrumentation: "acoustic, folk, warm group",
    key: "G major",
    dynamics: "warm, lively",
    musicPrompt: "acoustic folk, warm, lively, feast, convivial, joyful, group, celebration, major key",
  },
  {
    id: "arch_108",
    text: "the sorrow of a relationship that should have worked but did not",
    mood: "relationship sorrow",
    tempo: "slow",
    texture: "unresolved, sad",
    instrumentation: "piano, guitar, sparse strings",
    key: "E minor",
    dynamics: "quiet, aching",
    musicPrompt: "piano, guitar, sparse strings, relationship, sorrow, aching, minor key, slow, intimate",
  },
  {
    id: "arch_109",
    text: "watching a fire burn, hypnotized by the flames",
    mood: "fire hypnosis",
    tempo: "slow, undulating",
    texture: "warm, flickering",
    instrumentation: "guitar, ambient, crackling warmth",
    key: "E minor",
    dynamics: "warm, undulating",
    musicPrompt: "guitar, ambient warmth, crackling, hypnotic, fire, slow, undulating, meditative, warm",
  },
  {
    id: "arch_110",
    text: "the hollow victory of winning an argument you wish you had not had",
    mood: "hollow victory",
    tempo: "moderate, flat",
    texture: "empty resolution",
    instrumentation: "piano, brief resolution, silence",
    key: "C major then silence",
    dynamics: "resolving then empty",
    musicPrompt: "piano, brief resolution, hollow, empty victory, minor to empty, quiet, unsatisfying close",
  },
  {
    id: "arch_111",
    text: "falling into a rabbit hole of research, hours disappearing",
    mood: "research rabbit hole",
    tempo: "moderate, continuous",
    texture: "flowing, layering",
    instrumentation: "minimal piano, building layers",
    key: "D minor",
    dynamics: "continuous, building layers",
    musicPrompt: "piano, building layers, continuous, research, absorbed, flowing, modern classical, intellectual",
  },
  {
    id: "arch_112",
    text: "the specific calm of a long flight at night above the clouds",
    mood: "above the clouds calm",
    tempo: "very slow, floating",
    texture: "vast, airy",
    instrumentation: "ambient synth, piano, vast space",
    key: "Eb major",
    dynamics: "quiet, expansive",
    musicPrompt: "ambient synth, piano, vast, floating, above clouds, night flight, calm, expansive, airy",
  },
  {
    id: "arch_113",
    text: "the tenderness of caring for someone sick",
    mood: "tender care",
    tempo: "slow, gentle",
    texture: "soft, attentive",
    instrumentation: "piano, soft strings, gentle",
    key: "F major",
    dynamics: "soft, gentle",
    musicPrompt: "piano, soft strings, tender, caring, gentle, warm, soft, heartfelt, intimate, slow",
  },
  {
    id: "arch_114",
    text: "the exhilaration of almost missing something but making it just in time",
    mood: "near miss relief",
    tempo: "fast then releasing",
    texture: "tense then releasing",
    instrumentation: "strings, brass, releasing",
    key: "D major",
    dynamics: "tense then bright relief",
    musicPrompt: "strings, brass, tension to release, near miss, exhilarating, relief, cinematic, major, bright",
  },
  {
    id: "arch_115",
    text: "a memory so specific and distant it feels like it belongs to someone else",
    mood: "distant memory",
    tempo: "slow, hazy",
    texture: "faded, distant",
    instrumentation: "piano, vintage textures, reverb",
    key: "G major",
    dynamics: "soft, faded",
    musicPrompt: "piano, vintage reverb, faded, distant memory, slow, hazy, nostalgic, intimate, old recording",
  },
  {
    id: "arch_116",
    text: "the exquisite pain of a song that hits too close to the truth",
    mood: "song catharsis",
    tempo: "moderate, emotional",
    texture: "raw, resonant",
    instrumentation: "piano, strings, raw",
    key: "A minor",
    dynamics: "building, cathartic",
    musicPrompt: "piano, strings, raw emotion, cathartic, resonant, building, hitting truth, emotional, cinematic",
  },
  {
    id: "arch_117",
    text: "standing at a window watching rain and thinking about everything",
    mood: "rainy window thinking",
    tempo: "slow, drifting",
    texture: "soft, grey",
    instrumentation: "piano, rain sounds, sparse",
    key: "D minor",
    dynamics: "soft, contemplative",
    musicPrompt: "piano, rain sounds, contemplative, drifting, window, grey, soft, introspective, slow",
  },
  {
    id: "arch_118",
    text: "the terror and thrill of being truly seen by another person",
    mood: "seen terror-joy",
    tempo: "moderate, trembling",
    texture: "exposed, trembling",
    instrumentation: "piano, fragile strings, opening",
    key: "E minor to major",
    dynamics: "fragile then warm",
    musicPrompt: "piano, fragile strings, exposed, vulnerable, seen, trembling, minor to warm major, intimate",
  },
  {
    id: "arch_119",
    text: "the momentum of a plan finally coming together",
    mood: "plan momentum",
    tempo: "building, purposeful",
    texture: "layering, building",
    instrumentation: "strings, brass, layering elements",
    key: "D major",
    dynamics: "building, purposeful",
    musicPrompt: "strings, brass, building layers, momentum, purposeful, coming together, cinematic, major, driving",
  },
  {
    id: "arch_120",
    text: "the resignation of accepting you cannot change someone",
    mood: "letting go resignation",
    tempo: "slow, settling",
    texture: "heavy then settling",
    instrumentation: "piano, low strings, settling",
    key: "C minor",
    dynamics: "heavy then quiet resignation",
    musicPrompt: "piano, low strings, resignation, letting go, heavy, settling, quiet, minor key, accepting",
  },
  {
    id: "arch_121",
    text: "joy of the first warm day after a long winter",
    mood: "first warmth",
    tempo: "moderate, brightening",
    texture: "brightening, fresh",
    instrumentation: "piano, strings, woodwinds, fresh",
    key: "E major",
    dynamics: "brightening, warm",
    musicPrompt: "piano, strings, woodwinds, first spring warmth, bright, fresh, hopeful, major key, light",
  },
  {
    id: "arch_122",
    text: "having to be strong for someone else when you are falling apart inside",
    mood: "internal collapse external strength",
    tempo: "steady, strained",
    texture: "surface calm, inner chaos",
    instrumentation: "steady melody, dissonant undercurrent",
    key: "G minor",
    dynamics: "outwardly steady, inner tension",
    musicPrompt: "steady melody, dissonant undertones, strength and collapse, strained, cinematic, minor key",
  },
  {
    id: "arch_123",
    text: "nostalgia for the future, mourning a life you will not live",
    mood: "future nostalgia",
    tempo: "slow, wistful",
    texture: "dream-like, distant",
    instrumentation: "piano, hazy synth, strings",
    key: "A major",
    dynamics: "soft, wistful",
    musicPrompt: "piano, hazy synth, strings, wistful, future nostalgia, dreaming, soft, bittersweet, ambient",
  },
  {
    id: "arch_124",
    text: "the strange intimacy of being strangers on a long journey",
    mood: "stranger intimacy",
    tempo: "moderate, passing",
    texture: "brief, warm",
    instrumentation: "guitar, piano, gentle",
    key: "C major",
    dynamics: "warm but transient",
    musicPrompt: "guitar, piano, gentle, strangers, brief intimacy, transient, warm, passing, indie folk",
  },
  {
    id: "arch_125",
    text: "the relief of finally crying after holding it together too long",
    mood: "long-awaited release",
    tempo: "slow, releasing",
    texture: "held then releasing",
    instrumentation: "piano, strings releasing",
    key: "F minor to major",
    dynamics: "held tension then release",
    musicPrompt: "piano, strings, held tension releasing, crying release, cathartic, minor to major, emotional",
  },
  {
    id: "arch_126",
    text: "competition, wanting to win more than anything",
    mood: "competitive drive",
    tempo: "fast, driving",
    texture: "tight, aggressive",
    instrumentation: "drums, brass, driving strings",
    key: "E minor",
    dynamics: "intense, driving",
    musicPrompt: "drums, brass, driving strings, competitive, aggressive, fast, intense, sports, cinematic",
  },
  {
    id: "arch_127",
    text: "the calm that settles after a big argument is resolved",
    mood: "post-argument calm",
    tempo: "slow, exhaling",
    texture: "heavy then settling",
    instrumentation: "piano, strings settling",
    key: "F major",
    dynamics: "heavy then gentle",
    musicPrompt: "piano, strings, exhaling, post-argument, settling, calm, gentle, warm, resolved, slow",
  },
  {
    id: "arch_128",
    text: "feeling the presence of someone who has passed",
    mood: "presence of the gone",
    tempo: "very slow, hushed",
    texture: "thin, delicate",
    instrumentation: "solo piano, ambient, silence",
    key: "D major",
    dynamics: "very soft, present",
    musicPrompt: "solo piano, ambient, presence, spiritual, gentle, hushed, silence, warm, ethereal",
  },
  {
    id: "arch_129",
    text: "the vertigo of realizing how much time has passed",
    mood: "time vertigo",
    tempo: "slow, then faster, disorienting",
    texture: "swirling, disorienting",
    instrumentation: "piano, strings, warped time",
    key: "modal",
    dynamics: "disorienting swells",
    musicPrompt: "piano, strings, warped, time passing, vertigo, disorienting, swelling, ambient, cinematic",
  },
  {
    id: "arch_130",
    text: "the specific joy of solving a hard problem",
    mood: "problem-solving joy",
    tempo: "moderate then bright",
    texture: "building then bright",
    instrumentation: "piano, strings, bright resolution",
    key: "C major",
    dynamics: "building then bright release",
    musicPrompt: "piano, strings, building to bright resolution, eureka, joy, solving, intellectual, cinematic",
  },
  {
    id: "arch_131",
    text: "the shame and courage of starting over",
    mood: "starting over",
    tempo: "slow then rising",
    texture: "heavy then cautiously rising",
    instrumentation: "piano, cautiously building strings",
    key: "A minor to major",
    dynamics: "heavy then cautious hope",
    musicPrompt: "piano, strings, heavy to cautious hope, starting over, shame and courage, cinematic, minor to major",
  },
  {
    id: "arch_132",
    text: "joy of good news after a long wait",
    mood: "good news relief-joy",
    tempo: "fast, suddenly bright",
    texture: "bright burst",
    instrumentation: "piano, strings, bright",
    key: "G major",
    dynamics: "suddenly bright and full",
    musicPrompt: "piano, strings, bright burst, good news, sudden joy, relief, major key, celebratory, emotional",
  },
  {
    id: "arch_133",
    text: "the quiet of being the only one awake in a sleeping house",
    mood: "only one awake",
    tempo: "very slow, quiet",
    texture: "sparse, intimate",
    instrumentation: "solo piano, breath, silence",
    key: "C major",
    dynamics: "barely there, intimate",
    musicPrompt: "solo piano, breath, silence, only one awake, quiet house, intimate, sparse, midnight, peaceful",
  },
  {
    id: "arch_134",
    text: "fury at injustice, burning desire for things to be right",
    mood: "righteous fury",
    tempo: "fast, driving",
    texture: "hot, powerful",
    instrumentation: "full orchestra, brass, drums",
    key: "D minor",
    dynamics: "powerful, building",
    musicPrompt: "full orchestra, brass, drums, righteous fury, driving, powerful, cinematic, intense, justice",
  },
  {
    id: "arch_135",
    text: "the specific peace of doing something with your hands",
    mood: "craft absorption",
    tempo: "moderate, steady",
    texture: "warm, rhythmic",
    instrumentation: "guitar, piano, gentle rhythm",
    key: "D major",
    dynamics: "steady, warm",
    musicPrompt: "guitar, piano, gentle rhythm, craft, hands, absorbed, warm, steady, folk, peaceful",
  },
  {
    id: "arch_136",
    text: "loving someone despite knowing their flaws completely",
    mood: "imperfect love",
    tempo: "moderate, warm",
    texture: "full, honest",
    instrumentation: "piano, guitar, strings",
    key: "G major",
    dynamics: "warm, honest",
    musicPrompt: "piano, guitar, strings, imperfect love, honest, warm, full, major key, heartfelt, real",
  },
  {
    id: "arch_137",
    text: "being in nature and feeling the smallness of human problems",
    mood: "nature perspective",
    tempo: "slow, expansive",
    texture: "vast, natural",
    instrumentation: "ambient, strings, nature sounds",
    key: "D major",
    dynamics: "expansive, peaceful",
    musicPrompt: "ambient, strings, nature sounds, vast, perspective, peaceful, expansive, cinematic, natural",
  },
  {
    id: "arch_138",
    text: "the silliness and joy of inside jokes with a best friend",
    mood: "best friend silliness",
    tempo: "fast, playful",
    texture: "light, laughing",
    instrumentation: "playful piano, percussion, light",
    key: "C major",
    dynamics: "light, playful",
    musicPrompt: "playful piano, light percussion, silly, joyful, friends, laughing, bouncy, playful, fun",
  },
  {
    id: "arch_139",
    text: "the weight of carrying a secret for too long",
    mood: "secret burden",
    tempo: "slow, heavy",
    texture: "compressed, heavy",
    instrumentation: "low strings, piano, weight",
    key: "B minor",
    dynamics: "heavy, compressed",
    musicPrompt: "low strings, piano, heavy, secret, burden, compressed, slow, dark, minor key, weighted",
  },
  {
    id: "arch_140",
    text: "the specific excitement of a new creative project beginning",
    mood: "creative beginning",
    tempo: "moderate, energized",
    texture: "fresh, possibility",
    instrumentation: "piano, light strings, possibility",
    key: "E major",
    dynamics: "bright, energized",
    musicPrompt: "piano, light strings, bright, new project, creative, energized, possibility, hopeful, major",
  },
  {
    id: "arch_141",
    text: "sitting with uncertainty and choosing to be okay with not knowing",
    mood: "accepting uncertainty",
    tempo: "slow, breathing",
    texture: "open, unresolved",
    instrumentation: "piano, open harmonics",
    key: "modal, unresolved",
    dynamics: "soft, open",
    musicPrompt: "piano, open harmonics, unresolved, accepting uncertainty, breathing, soft, ambient, modal",
  },
  {
    id: "arch_142",
    text: "the excitement of a city at night, lights and energy",
    mood: "city night energy",
    tempo: "fast, pulsing",
    texture: "bright, electric",
    instrumentation: "synths, drums, bass, city",
    key: "A minor",
    dynamics: "electric, pulsing",
    musicPrompt: "synths, drums, bass, city night, electric, pulsing, fast, urban, exciting, electronic",
  },
  {
    id: "arch_143",
    text: "the tenderness of watching something old and beloved falling apart",
    mood: "beloved decay",
    tempo: "slow, gentle",
    texture: "fragile, fading",
    instrumentation: "piano, crackle, fading strings",
    key: "F major",
    dynamics: "gentle, fading",
    musicPrompt: "piano, vinyl crackle, fading strings, tender, beloved, fragile decay, gentle, warm, fading",
  },
  {
    id: "arch_144",
    text: "the strange mix of pride and heartbreak when someone leaves to pursue their dreams",
    mood: "proud heartbreak",
    tempo: "slow, complex",
    texture: "bittersweet, complex",
    instrumentation: "piano, strings, complex",
    key: "D minor to major",
    dynamics: "complex, layered",
    musicPrompt: "piano, strings, proud heartbreak, bittersweet, complex, minor to major, layered, cinematic",
  },
  {
    id: "arch_145",
    text: "the realization you have become the person you needed when you were younger",
    mood: "self-completion",
    tempo: "moderate, warm",
    texture: "full, complete",
    instrumentation: "piano, full strings, resolved",
    key: "C major",
    dynamics: "warm, complete",
    musicPrompt: "piano, full strings, complete, self, warm, resolved, cinematic, major, heartfelt, arriving",
  },
  {
    id: "arch_146",
    text: "being betrayed by someone you completely trusted",
    mood: "betrayal shock",
    tempo: "moderate then collapsing",
    texture: "shattering",
    instrumentation: "piano, strings breaking apart",
    key: "E minor",
    dynamics: "collapsing, shattering",
    musicPrompt: "piano, strings breaking, betrayal, shock, shattering, collapsing, dark, intense, minor, cinematic",
  },
  {
    id: "arch_147",
    text: "the specific joy of pets, their uncomplicated love",
    mood: "pet joy",
    tempo: "moderate, warm",
    texture: "warm, simple",
    instrumentation: "piano, light percussion, simple melody",
    key: "G major",
    dynamics: "warm, simple",
    musicPrompt: "piano, light percussion, simple, warm, uncomplicated love, pet, joyful, gentle, major key",
  },
  {
    id: "arch_148",
    text: "existential wonder at the universe, stars and time and infinity",
    mood: "cosmic wonder",
    tempo: "very slow, vast",
    texture: "infinite, vast",
    instrumentation: "synths, ambient, deep space",
    key: "modal",
    dynamics: "vast, quiet wonder",
    musicPrompt: "synths, ambient, deep space, cosmic, vast, infinity, wonder, slow, epic ambient, universe",
  },
  {
    id: "arch_149",
    text: "the specific warmth of being welcomed home after a long time away",
    mood: "welcomed home",
    tempo: "moderate, warm",
    texture: "full, arriving",
    instrumentation: "piano, strings, warm arrival",
    key: "G major",
    dynamics: "warm, full",
    musicPrompt: "piano, strings, warm arrival, home, welcomed, full, major key, heartfelt, cinematic, returning",
  },
  {
    id: "arch_150",
    text: "the strange sadness of happiness, knowing it will end",
    mood: "happiness tinged with loss",
    tempo: "moderate, glowing but wistful",
    texture: "warm but aware",
    instrumentation: "piano, strings, bittersweet warmth",
    key: "D major with shadows",
    dynamics: "warm but wistful",
    musicPrompt: "piano, strings, bittersweet warmth, happiness tinged with loss, wistful, major, glowing, aware",
  },
];
